packages:
  - addon
  - test-app
onlyBuiltDependencies:
  - core-js
  - fsevents
# Be a good citizen of the ecosystem. If a dep is not declared, we want an error
autoInstallPeers: false
strictPeerDependencies: true
resolvePeersFromWorkspaceRoot: false
